### ISSUE TITLE
iS LLMA lossless?

### ISSUE THREAD

**Issue by riyaj8888** [microsoft/LMOps#155]
For few samples we are getting different outputs from greedy and llma decoding .
why its happening ? is there bug in the code or its expected behaviour.

**Comment by nyanyanya** [comment]
The algorithm is designed to be lossless if the computation is done at infinity precision. In reality the computation is done at 32 or 16-bit precision, which might cause some discrepancies due to rounding errors.
In our test, such cases are extremely rare. If you encounter frequent differences between greedy and llma outputs, it must be some bugs or errors we are not aware of.
