### ISSUE TITLE
[Instruction-pretrain] Questions regarding the format of general instructions mixed in the pretraining corpus

### ISSUE THREAD

**Issue by Vispstar-V** [microsoft/LMOps#257]
Hi, I'm a reader of the work "Instruction Pre-Training: Language Models are Supervised Multitask Learners." 
Currently, I'm trying to replicate the results of vanilla continual pre-training on Llama3-8B. I have noticed that in both your paper and [your dataset card](https://huggingface.co/datasets/instruction-pretrain/medicine-instruction-augmented-corpora), a 1:1 ratio of general instructions is mixed with the domain corpus for CPT. So I was wondering how this part of the data looks like. 
Do you use the official Llama3 prompt, like
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{sys_prompt}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{user_input}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n
```
or do you simply concatenate each instruction with its output using '\n', like those domain instruction-response pairs? 

Could you please clarify this for me? Many thanks!

**Comment by cdxeve** [comment]
Thanks for your interest.

**Q1: Do you use the official Llama3 prompt?**

No, the provided Llama3 prompt is designed for the [instruction-tuned model](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct), but our continual pre-training is conducted on the [pre-trained base model](https://huggingface.co/meta-llama/Meta-Llama-3-8B) where only BOS (`<|begin_of_text|>`) and EOS (`<|end_of_text|>`) tokens are required.

**Q2: Do you simply concatenate each instruction with its output using '\n', like those domain instruction-response pairs?**

No, as mentioned in the pre-training suggestions from [instruction-synthesizer](https://huggingface.co/instruction-pretrain/instruction-synthesizer), we use a simple whitespace to concatenate each question with its response for the general instruction data from OpenOrca. This is because OpenOrca's data is already templated with diverse natural languge templates (such as those with `\n`), so a whitespace is sufficient to formulate the data.

Note that when using our templated instruction-augmented texts, you don't need to add any concatenations.

**To put it all together, the text before tokenization looks like this:**

`general_instruction_response_text = "<|begin_of_text|>{question} {response}<|end_of_text|>"`

or

`instruction_augmented_text = "<|begin_of_text|>{instruction augmented text}<|end_of_text|>"`

Then, for tokenization, you don't need to add BOS and EOS token ids. The tokenization code looks like this:

`text_ids = tokenizer(text, add_special_tokens=False, **kwargs).input_ids`

**Comment by Vispstar-V** [comment]
Thanks for your detailed response! I have one more question: what about those system prompts in OpenOrca? Do you also concatenate them before the instructions using whitespace or simply discard those?

**Comment by cdxeve** [comment]
Yes, we simply discard the system prompts.
