### ISSUE TITLE
[minillm] how to resume training when it occurs some bugs during running file 'train_minillm.py'?

### ISSUE THREAD

**Issue by chentianyangWHU** [microsoft/LMOps#61]
I ran 'train_minillm.py' successfully under the guidance of the README.md file. However, due to some uncontrollable factors, the GPU will interrupt approximately every 6-8 hours. At this time, the locally saved files are shown in the following figure. How should I continue the interrupted training? Thanks a lot!
![image](https://github.com/microsoft/LMOps/assets/39194717/09c79038-604d-4e07-a63d-c74ad7e3cd30)

**Comment by t1101675** [comment]
We didn't strictly implement resuming training from certain checkpoints because we didn't save the optimizer's state due to its large storage occupation. 

However, you can try an approximate version by first changing the `CKPT` variable in `[train_7B_13B.sh](https://github.com/microsoft/LMOps/blob/main/minillm/scripts/llama/minillm/train_7B_13B.sh)` to the path of the latest checkpoint. Then, manually skip a certain number of training steps by adding codes like 
```python
if self.global_iter_count <= 1000:
    self.iter_count += 1
    if self.iter_count % self.args.gradient_accumulation_steps == 0:
        self.global_iter_count += 1
        self.scheduler.step()
    continue
```
to this [line](https://github.com/microsoft/LMOps/blob/3fa73d45da39c49cf6c232ad8e16120eb441c9eb/minillm/minillm/trainer.py#L269).

Note that this may not guarantee the exact same training dynamics as the previous training because we didn't load the optimizer states. 

May be we will consider add the training resuming feature in the next version.

**Comment by donglixp** [comment]
> We didn't strictly implement resuming training from certain checkpoints because we didn't save the optimizer's state due to its large storage occupation.
> 
> However, you can try an approximate version by first changing the `CKPT` variable in `[train_7B_13B.sh](https://github.com/microsoft/LMOps/blob/main/minillm/scripts/llama/minillm/train_7B_13B.sh)` to the path of the latest checkpoint. Then, manually skip a certain number of training steps by adding codes like
> 
> ```python
> if self.global_iter_count <= 1000:
>     self.iter_count += 1
>     if self.iter_count % self.args.gradient_accumulation_steps == 0:
>         self.global_iter_count += 1
>         self.scheduler.step()
>     continue
> ```
> 
> to this [line](https://github.com/microsoft/LMOps/blob/3fa73d45da39c49cf6c232ad8e16120eb441c9eb/minillm/minillm/trainer.py#L269).
> 
> Note that this may not guarantee the exact same training dynamics as the previous training because we didn't load the optimizer states.
> 
> May be we will consider add the training resuming feature in the next version.

@chentianyangWHU Contributions are welcome.

**Comment by chentianyangWHU** [comment]
thank you!
